name: Workflow CI

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Run Ruff Linter
        run: uvx ruff check --fix .

      - name: Run Ruff Formatter
        run: uvx ruff format --check .

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          SECRET_KEY: test_secret_key
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          FRONTEND_URL: http://localhost:3000
          GOOGLE_API_KEY: test_key
          HF_TOKEN: test_token
          DATABASE_URL: sqlite:///./test.db
          ENDPOINT: http://localhost:8000
          KEY: test_key
        run: uv run pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: [ruff, pytest]
    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          path: HR-Pulse

      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: codehass/HR-Pulse-frontend
          path: HR-Pulse-frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        working-directory: HR-Pulse
        run: |
          docker compose build
